---

external_interface: "eth0"

internal_interface: "eth1" 
int_net_addr: "10.0.0.0"
int_ip_addr: "10.1.1.3"
int_net_mask: "255.0.0.0"
int_gateway: "10.1.1.4"

internal_ip: "{{int_ip_addr}}"
internal_net: "10.0.0.0/8"

network_ether_interfaces:
  - device: "{{external_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{ext_ip_addr}}"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    defroute: "yes"
    nm_controlled: "no"
    type: "Ethernet"
    route:
      - network: "{{ext_net_addr}}"
        netmask: "{{ext_net_mask}}"
        gateway: "{{ext_gateway}}"

  - device: "{{internal_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{int_ip_addr}}"
    netmask: "{{int_net_mask}}"
    nm_controlled: "no"
    type: "Ethernet"

vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"
disks:
  - { path: "/var/vms/grid.raw", size: 200 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "grid"
fqdn: "{{siteName}}-grid.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver2}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
root_password: "{{ lookup('password', 'credentials/'+ inventory_hostname  +'_rootpw length=15') }}"

# Slurm
slurm_type: "submit"

# Ferm - firewall
ferm_rules_extra:
 grid:
 - chain: INPUT
   table: filter
   domains: [ip]
   rules:
     - {rule: "proto tcp dport (443) mod state state (NEW) mod comment comment 'Allow new 443' ACCEPT;", comment: "Allow HTTPS to grid Frontend"}
     - {rule: "proto tcp dport (8443) mod state state (NEW) mod comment comment 'Allow new 8443' ACCEPT;", comment: "Allow HTTPS to grid Frontend"}
     - {rule: "proto tcp dport (2811) mod state state (NEW) mod comment comment 'Allow new 2811' ACCEPT;", comment: "Allow 2811 to grid Frontend"}
     - {rule: "proto tcp dport (2135) mod state state (NEW) mod comment comment 'Allow new 2135' ACCEPT;", comment: "Allow BDII to grid Frontend"}
     - {rule: "proto tcp dport (20000:25000) mod state state (NEW) mod comment comment 'Allow new gridftp range' ACCEPT;", comment: "Allow gridftp to grid Frontend"}
 10_nat:
 - chain: FORWARD
   table: filter
   domains: [ip, ip6]
   rules:
     - {rule: "interface {{ internal_interface }} outerface {{ external_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward establish and related' ACCEPT;", comment: "forwarding"}
     - {rule: "interface {{ internal_interface }} outerface {{ external_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward from internal net' ACCEPT;", comment: "forwarding"}
 - chain: POSTROUTING
   table: nat
   domains: [ip]
   rules:
     - {rule: "daddr ( {{ trusted_public_networks }} {{ internal_net }} ) mod comment comment 'masquerade for internal net' ACCEPT;", comment: "masquerade"}
     - {rule: "outerface br_ext saddr ( {{ internal_net }} ) mod comment comment 'masquerade for internal net' MASQUERADE;", comment: "masquerade"}

#NTP
ntp_config_server: [ "{{ hostvars[groups['install'][0]]['ansible_hostname'] }}", "{{ hostvars[groups['admin'][0]]['ansible_hostname'] }}" ]

#CVMFS
cvmfs_http_proxy: "{{ http_proxy }}"
cvmfs_quota_limit: "10240"

# Do not extra install infiniband packages
infiniband_available: False

# SSH
sshd:
 AllowGroups: "root admin" 

# NFS mounts

nfs_mount: |
  10.2.1.5:/scratch /scratch                nfs4 defaults 0 0
  10.2.1.5:/home    /home                   nfs4 defaults 0 0

# ARC Frontend vars

## Set this as "true" in full cluster install; Set them back to "false" afterwards!
arc_frontend_nis: false
add_slurm_accts: false

slurm_wakeupperiod: "60"

globus_tcp_port_range: "20000,25000"
globus_udp_port_range: "20000,25000"

x509_user_key: "/etc/grid-security/hostkey.pem"
x509_user_cert: "/etc/grid-security/hostcert.pem"
x509_cert_dir: "/etc/grid-security/certificates"

gridmap: "/etc/grid-security/grid-mapfile"
voms_processing: "strict"

controldir: "/var/spool/nordugrid/jobstatus"
arc_frontend_griddir: "/scratch/grid"
arc_frontend_sessiondir: "{{ griddir }}/sessiondir"
arc_frontend_runtimedir: "{{ griddir }}/runtime"
shared_scratch: "/scratch"

arc_frontend_cachedir: "/scratch/cache"
cachesize: "80 70"
cachelifetime: "60d"

logsize: "1000000 52"
shared_filesystem: "yes"
joblog: "/var/log/arc/gm-jobs.log"

maxjobs: "10000 10000 80"
wakeupperiod: "30"
defaultttl: "604800 1209600"
authplugin: "FINISHED timeout=30,onfailure=pass"
arex_mount_point: "https://{{ fqdn }}:443"
maxtransfertries: "10"

unixgroup_dir_ops: "/etc/grid-security/opspool"
unixgroup_dir_fgi: "/etc/grid-security/fgipool"

group_name_ops: "ops"
group_name_fgi: "fgi"

ops_acct_nr: 40
fgi_acct_nr: 200
