---
galaxy_info:
  author: "Philippe Dellaert"
  company: http://dellaert.org
  license: BSD
  min_ansible_version: 1.4
  platforms:
   - name: EL
     versions:
      - 5
      - 6
   - name: Fedora
     versions:
      - 16
      - 17
      - 18
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
   - name: Archlinux
     versions:
       - all
  categories:
   - system
   - networking
dependencies: []
