---
dnsmasq_port: 53

# Optional variables
dnsmasq_addn_hosts: null
dnsmasq_addresses: null
dnsmasq_bogus_nxdomain: null
dnsmasq_bogus_priv: null
dnsmasq_domain: null
dnsmasq_domain_needed: null
dnsmasq_expand_hosts: null
dnsmasq_external_servers: null
dnsmasq_forward_servers: null
dnsmasq_local_ttl: null
dnsmasq_log_dhcp: null
dnsmasq_log_queries: null
dnsmasq_no_dhcp: null
dnsmasq_no_hosts: null
dnsmasq_no_resolv: null
